- name: Повторная проверка APT
  when: ansible_os_family == "Debian"
  become: true # Убеждаемся, что запускаем от рута
  block:
    - name: Выполнить apt update повторно
      command: apt update
      register: final_apt_result
      changed_when: false
      failed_when: false # Специально не падаем здесь, чтобы увидеть вывод

    # --- ВОТ НАША ОТЛАДОЧНАЯ ЗАДАЧА ---
    - name: "ОТЛАДКА | Показать вывод финального apt update"
      ansible.builtin.debug:
        msg:
          - "====================== STDERR (ОШИБКА ДОЛЖНА БЫТЬ ЗДЕСЬ) ======================"
          - "{{ final_apt_result.stderr }}"
          - "====================== STDOUT (ОБЫЧНЫЙ ВЫВОД) ======================"
          - "{{ final_apt_result.stdout }}"
      when: final_apt_result is defined
    # ------------------------------------

    - name: Установить флаг финального успеха
      set_fact:
        final_check_successful: true
      when: final_apt_result.rc == 0

- name: Повторная проверка YUM
  when: ansible_os_family == "RedHat"
  become: true
  block:
    - name: Выполнить dnf makecache повторно
      command: dnf makecache
      register: final_yum_result
      changed_when: false
      failed_when: false

    - name: "ОТЛАДКА | Показать вывод финального dnf makecache"
      ansible.builtin.debug:
        msg:
          - "====================== STDERR (ОШИБКА БУДЕТ ЗДЕСЬ) ======================"
          - "{{ final_yum_result.stderr }}"
          - "====================== STDOUT (ОБЫЧНЫЙ ВЫВОД) ======================"
          - "{{ final_yum_result.stdout }}"
      when: final_yum_result is defined

    - name: Установить флаг финального успеха
      set_fact:
        final_check_successful: true
      when: final_yum_result.rc == 0

#- name: Проверка финального статуса
#  fail:
#    msg: "Финальная проверка репозиториев завершилась неудачно (см. вывод отладки выше)"
#  when: not final_check_successful | default(false)
